#!/usr/bin/python
# -*- coding: utf-8 -*-
# Copyright (C) 2010 Canonical
#
# Authors:
#  Didier Roche <didrocks@ubuntu.com>
#
# This program is free software; you can redistribute it and/or modify it under
# the terms of the GNU General Public License as published by the Free Software
# Foundation; version 3.
#
# This program is distributed in the hope that it will be useful, but WITHOUT
# ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
# FOR A PARTICULAR PURPOSE.  See the GNU General Public License for more
# details.
#
# You should have received a copy of the GNU General Public License along with
# this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA

import gobject
from dbus.mainloop.glib import DBusGMainLoop

from oneconf.dbusconnect import DbusHostsService

MIN_TIME_WITHOUT_ACTIVITY = 30

def quit(loop, myservice):
    '''quit if no activity at least in 30s'''
    if myservice.activity:
        myservice.activity = False
        return True
    loop.quit()

if __name__ == '__main__':
    DBusGMainLoop(set_as_default=True)
    loop = gobject.MainLoop()
    myservice = DbusHostsService()
    gobject.timeout_add_seconds(MIN_TIME_WITHOUT_ACTIVITY, quit, loop, myservice)
    loop.run()

