#!/bin/sh
# autopkgtest check: Run the upstream unittests.
# (C) 2013 Canonical Ltd.
# Author: Barry Warsaw <barry@ubuntu.com>

set -ex

# It's enough that this doesn't fail.
/usr/bin/oneconf-query --version
